[package]
name = "day2"
version = "0.1.0"
authors = ["Brian Hsu <brian@brianhsu.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
